name: Destroying Terraform Resources

on:
  workflow_dispatch:

jobs:
  TERRAFORM_DESTROY:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Setting Up Terraform
       uses: hashicorp/setup-terraform@v1

     - name: Configuring AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

     - name: Terraform Destroy
       run: |
        - terraform init  
        - terraform destroy -auto-approve
       working-directory: main 




