name: Docker workflow

on:
  workflow_dispatch

jobs:
  build_image:
    name: Building docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Building docker image
        run: docker build -t goals-image:latest .
        working-directory: goals-app

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: goals-image:latest
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  deploy_image_to_ecr:
        name: Deploying image to AWS ECR
        needs: build_image
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Configuring AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: us-east-1
         
          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v1
            with:
              mask_password: "true"

          - name: Tagging Docker Image
            run: docker tag goals-image:latest ${{ secrets.ECR_REGISTRY }}
            working-directory: goals-app

          - name: Pushing Docker Image
            run: docker push ${{ secrets.ECR_REGISTRY }}
            working-directory: goals-app

  